name: buildfork

on:
  workflow_dispath

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v4
   -name: cache
   uses: actions/cache@v4.0.0
   with:
    path: -/.npm
    key: buildCache
    - run: npm ci
    - run: npm -- --coverage
      env:
      CI: true
    - name: Upload code coverage
      uses: actions/upload-artifact@4.3.1
      with
       name: code coverage
       path: coverage

      - name: build
        run: npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v3.1.0
        with
         name: build
         path: build
         
